version: "3.9"
services:
  db:
    image: postgres
    container_name: confia-db
    restart: unless-stopped
    env_file: 
      - .env
    ports:
      - 15432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - confianet
  pgadmin:
    image: dpage/pgadmin4
    container_name: confia-pgadmin
    env_file: 
      - .env
    ports:
      - "16543:80"
    depends_on:
      - db
networks:
  default:
    external:
      name: confia
